### ISSUE TITLE
Progress test not being picked up

### ISSUE THREAD

**Issue by andre-gh** [Modernizr/customizr#23]
I tried various variations of progressbar meter and I could not get it to include (including just "progressbar" alone and "progress") and `["progressbar", "meter"]`

the property test defines`"property": ["progressbar", "meter"]` but the code appears to just look for a test where property is equal, is this the issue?

**Comment by backflip** [comment]
Looks very much like it, there is an [identical issue](https://github.com/Modernizr/customizr/issues/29) with `excludeTests` and replacing https://github.com/Modernizr/customizr/blob/develop/src/crawler.js#L171 and https://github.com/Modernizr/customizr/blob/develop/src/crawler.js#L189 with `return JSON.stringify(data.property) === JSON.stringify(test);` seems to work around it.

**Comment by rejas** [comment]
The issue with property arrays got fixed in v1 via https://github.com/Modernizr/customizr/pull/44 but the exclude part of this issue not. 
@backflip you want to provide a PR to fix https://github.com/Modernizr/customizr/issues/29 ?
@patrickkettner this issue itself can be closed, work should be done in #29
